DROP TABLE IF EXISTS T_USER_LOG;

CREATE TABLE T_USER_LOG (USER_ID INT
			,NAME STRING
			,SITE STRING)
PARTITIONED BY (DT STRING,COUNTRY STRING)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY '\t'
STORED AS TEXTFILE
;

